### ISSUE TITLE
FBSDK several issues with Version 4.25.0 in Corekit

### ISSUE THREAD

**Issue by Otto-munch** [facebook/facebook-sdk-swift#167]
<img width="1034" alt="bildschirmfoto 2017-08-01 um 18 57 13" src="https://user-images.githubusercontent.com/10657469/28837044-a404c1ea-76eb-11e7-84c0-93624bd4e803.png">

There are two semantic issues. My coworkers are using the 4.24.0 Version and don't have the issues. We are developing with xcode 9 beta

**Comment by michaelcordero** [comment]
I also have this same issue. Downgrading to 4.24 for FBSDKCoreKit, FBSDKLoginKit, and FBSDKShareKit resolves the problem.
<img width="1788" alt="screen shot 2017-08-14 at 10 14 21 pm" src="https://user-images.githubusercontent.com/8487086/29301478-16d0d0f0-8142-11e7-9d5b-7544159b7741.png">

**Comment by Otto-munch** [comment]
@michaelcordero Yeah right that's what my colleagues suggested too! Fortunately we fixed the problem. What kind of Beta are you using? When I updated to Xcode 9, Beta 5 I resolved this issue.

**Comment by Anu-Ujin** [comment]
@Otto-munch Does fbsdk version 4.25.0 support for xcode 9?

**Comment by Otto-munch** [comment]
@Anu-Ujin with the current version of xcode everything is working fine again!

**Comment by gfosco** [comment]
4.27.1 and 0.3.0 should resolve your issues.

**Comment by roceller** [comment]
I got Xcode Version 9.0.1 (9A1004)

FBSDKCoreKit (4.27.1)
FBSDKLoginKit (4.27.1) 
FBSDKShareKit (4.27.1)
FacebookCore (0.3.0)
FacebookLogin (0.3.0)
FacebookShare (0.3.0)

I still get this Semantic Issue warnings.

**Comment by justnealpatel** [comment]
Can all the semantic warning issues be ignored or are they worth looking into? It's a different story if they are actually errors. All I seem to be getting are a bunch of warnings, but the app still runs normally.
